apiVersion: v1
kind: Pod
metadata:
  name: ingot
  namespace: gold
spec:
  containers:
  - name: app
    image: alpine
    command: ["/bin/sh", "-c"]
    resources:
      requests:
        memory: "200Mi"
      limits:
        memory: "400Mi"
